server {
    listen 127.0.0.1:8080;
    server_name localhost;

    client_max_body_size 10m;


    location /cgi {
        root ./www;
        allow_methods GET POST;
        cgi_pass ./cgi-bin;
        autoindex off;
    }
}
