#ifndef CONSTANTS_HPP
# define CONSTANTS_HPP

# include <string>

// GENERAL

const int SUCCESS = 0;
const int FAILURE = -1;
const int UNDEFINED = -2;
const int INVALID_FD = -1;
const int MAX_UPLOAD_SIZE = 10 * 1024 * 1024;

// HTTP SERVER CONSTANTS
const int DEFAULT_PORT = 8080;
const std::string DEFAULT_HOST = "0.0.0.0";
const int DEFAULT_MAX_BODY_SIZE = 1000000;
const int DEFAULT_TIMEOUT = 60;

// HTTP STATUS CODES - HTTP - The Definitive Guide (p.505-507)
// for full HTTP/1.1 compliance requires responses to include both the status code and reason phrase
enum HttpStatus {
	// 1xx Informational
	HTTP_CONTINUE = 100,
	HTTP_SWITCHING_PROTOCOLS = 101,

	// 2xx Success
	HTTP_OK = 200,
	HTTP_CREATED = 201,
	HTTP_ACCEPTED = 202,
	HTTP_NON_AUTHORITATIVE_INFO = 203,
	HTTP_NO_CONTENT = 204,
	HTTP_RESET_CONTENT = 205,
	HTTP_PARTIAL_CONTENT = 206,

	// 3xx Redirection
	HTTP_MULTIPLE_CHOICES = 300,
	HTTP_MOVED_PERMANENTLY = 301,
	HTTP_FOUND = 302,
	HTTP_SEE_OTHER = 303,
	HTTP_NOT_MODIFIED = 304,
	HTTP_USE_PROXY = 305,
	HTTP_TEMPORARY_REDIRECT = 307,

	// 4xx Client Errors
	HTTP_BAD_REQUEST = 400,
	HTTP_UNAUTHORIZED = 401,
	HTTP_PAYMENT_REQUIRED = 402,
	HTTP_FORBIDDEN = 403,
	HTTP_NOT_FOUND = 404,
	HTTP_METHOD_NOT_ALLOWED = 405,
	HTTP_NOT_ACCEPTABLE = 406,
	HTTP_PROXY_AUTH_REQUIRED = 407,
	HTTP_REQUEST_TIMEOUT = 408,
	HTTP_CONFLICT = 409,
	HTTP_GONE = 410,
	HTTP_LENGTH_REQUIRED = 411,
	HTTP_PRECONDITION_FAILED = 412,
	HTTP_PAYLOAD_TOO_LARGE = 413,
	HTTP_URI_TOO_LONG = 414,
	HTTP_UNSUPPORTED_MEDIA_TYPE = 415,
	HTTP_RANGE_NOT_SATISFIABLE = 416,
	HTTP_EXPECTATION_FAILED = 417,

	// 5xx Server Errors
	HTTP_INTERNAL_SERVER_ERROR = 500,
	HTTP_NOT_IMPLEMENTED = 501,
	HTTP_BAD_GATEWAY = 502,
	HTTP_SERVICE_UNAVAILABLE = 503,
	HTTP_GATEWAY_TIMEOUT = 504,
	HTTP_VERSION_NOT_SUPPORTED = 505
};

std::string	getReasonPhrase(int statusCode);

// HTTP Methods
const std::string HTTP_GET = "GET";
const std::string HTTP_POST = "POST";
const std::string HTTP_DELETE = "DELETE";

// HTTP Version
const std::string HTTP_VERSION = "HTTP/1.1";

// COLORS CODES
# define RESET "\033[0m"
# define RED "\033[31m"
# define GREEN "\033[32m"
# define BLUE "\033[34m"
# define PURPLE "\033[35m"
# define YELLOW "\033[33m"
# define CYAN "\033[36m"

// CONFIGURATION DIRECTIVE
// ERROR MESSAGES - GENERAL
// ERROR MESSAGES - FILE OPERATIONS
// ERROR MESSAGES - CGI OPERATIONS
// ERROR MESSAGES - HTTP REQUEST VALIDATION
// ERROR MESSAGES - PROTOCAL CONSTANTS

// MIME TYPES
// CGI ENVIRONMENT VARIABLES
// DEFAULT PATHS AND FILES


#endif
